output:main.o strict.o  pattern.o fuzzy.o
  gcc main.o strict.o pattern.o fuzzy.o  -o output
main.o:main.c
  gcc -c main.c
strict.o:strict.c
  gcc -c strict.c
pattern.o:pattern.c
  gcc -c pattern.c
fuzzy.o:fuzzy.c
  gcc -c fuzzy.c
